### ISSUE TITLE
Issue with sqlparse 0.4.1

### ISSUE THREAD

**Issue by elemoine** [peopledoc/septentrion#94]
With Septentrion 0.1.3 and sqlparse 0.4.1 we get this error at migration time:

```
Version 20.10
  [ ] Applying 20.10-0-version-ddl.sql ...Traceback (most recent call last):
  File "/home/nova/.virtualenvs/doctype_prediction/bin/septentrion", line 8, in <module>
    sys.exit(main())
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/septentrion/cli.py", line 184, in migrate_func
    migrate.migrate(stylist=style.stylist)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/septentrion/migrate.py", line 56, in migrate
    run_script(path)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/septentrion/migrate.py", line 143, in run_script
    script.run(db.get_connection())
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/septentrion/runner.py", line 118, in run
    block.run(cursor)
  File "/home/nova/.virtualenvs/doctype_prediction/lib/python3.7/site-packages/septentrion/runner.py", line 48, in run
    raise SQLRunnerException("sqlparse failed to properly split input")
septentrion.runner.SQLRunnerException: sqlparse failed to properly split input
script returned exit code 1
```

There wasn't any problem with sqlparse 0.3.1. So it looks like there's a change in sqlparse that breaks Septentrion.

**Comment by ewjoachim** [comment]
could you submit a small snippet of public SQL code that fails with sqlparse 0.4 ?

**Comment by elemoine** [comment]
We used an old version of Septentrion. The latest version of Septentrion doesn't have the problem. Problem solved.
